interface Records {
  id: number;
  name: string;
  image: string;
  department: string;
  designation: string;
  date: string;
  project: string;
  assignedHours: number;
  hours: number;
  description: string;
}

const records: Records[] = [
  {
    id: 1,
    name: "Jon Doe",
    image: "https://i.ibb.co/grkMRWb/Untitled-design-14.png",
    department: "Web Designer",
    designation: "Web Developer",
    date: "2024-05-02T19:32:10.000Z",
    project: "Video Calling App",
    assignedHours: 20,
    hours: 10,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 2,
    name: "Jane Smith",
    image: "https://i.ibb.co/VqBCp6h/Untitled-design-16.png",
    department: "Android Developer",
    designation: "Android Developer",
    date: "2024-05-02T19:32:10.000Z",
    project: "Video Calling App",
    assignedHours: 18,
    hours: 12,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 3,
    name: "Alice Johnson",
    image: "https://i.ibb.co/ccVZdHs/istockphoto-464628641-612x612.jpg",
    department: "Team Leader",
    designation: "Team Leader",
    date: "2024-05-02T19:32:10.000Z",
    project: "Video Calling App",
    assignedHours: 22,
    hours: 16,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 4,
    name: "Mike Williams",
    image: "https://i.ibb.co/df5Mdm8/Untitled-design-15.png",
    department: "Frontend Developer",
    designation: "Frontend Developer",
    date: "2024-05-02T19:32:10.000Z",
    project: "E-commerce Website",
    assignedHours: 25,
    hours: 18,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 5,
    name: "Emily Brown",
    image: "https://i.ibb.co/N1Q8t0B/Education.png",
    department: "Backend Developer",
    designation: "Backend Developer",
    date: "2024-05-02T19:32:10.000Z",
    project: "E-commerce Website",
    assignedHours: 30,
    hours: 22,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 6,
    name: "David Miller",
    image: "https://i.ibb.co/qRX9TQD/image.png",
    department: "Marketing Manager",
    designation: "Marketing Manager",
    date: "2024-05-02T19:32:10.000Z",
    project: "Digital Marketing Campaign",
    assignedHours: 15,
    hours: 8,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 7,
    name: "Sophia Martinez",
    image: "https://i.ibb.co/grkMRWb/Untitled-design-14.png",
    department: "Content Writer",
    designation: "Content Writer",
    date: "2024-05-02T19:32:10.000Z",
    project: "Digital Marketing Campaign",
    assignedHours: 12,
    hours: 6,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 8,
    name: "Jacob Wilson",
    image: "https://i.ibb.co/grkMRWb/Untitled-design-14.png",
    department: "HR Manager",
    designation: "HR Manager",
    date: "2024-05-02T19:32:10.000Z",
    project: "HR Management System",
    assignedHours: 18,
    hours: 14,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 9,
    name: "Olivia Lee",
    image: "https://i.ibb.co/grkMRWb/Untitled-design-14.png",
    department: "Finance Analyst",
    designation: "Finance Analyst",
    date: "2024-05-02T19:32:10.000Z",
    project: "Financial Reporting",
    assignedHours: 20,
    hours: 18,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 10,
    name: "William Anderson",
    image: "https://i.ibb.co/grkMRWb/Untitled-design-14.png",
    department: "Customer ",
    designation: "Customer ",
    date: "2024-05-02T19:32:10.000Z",
    project: "Customer Support Portal",
    assignedHours: 15,
    hours: 12,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 11,
    name: "Liam Harris",
    image: "https://i.ibb.co/grkMRWb/Untitled-design-14.png",
    department: "UI/UX Designer",
    designation: "UI/UX Designer",
    date: "2024-05-02T19:32:10.000Z",
    project: "Mobile App Redesign",
    assignedHours: 25,
    hours: 20,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 12,
    name: "Ella Clark",
    image: "https://i.ibb.co/grkMRWb/Untitled-design-14.png",
    department: "Product Manager",
    designation: "Product Manager",
    date: "2024-05-02T19:32:10.000Z",
    project: "New Product Launch",
    assignedHours: 30,
    hours: 28,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 13,
    name: "Noah Garcia",
    image: "https://i.ibb.co/grkMRWb/Untitled-design-14.png",
    department: "Data Analyst",
    designation: "Data Analyst",
    date: "2024-05-02T19:32:10.000Z",
    project: "Market Research",
    assignedHours: 18,
    hours: 16,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
];

export { records };
